=== VVATOR/jaxbPracticalTask/jaxb-serializer-bindings/src/main/resources/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="https://www.epam.com/products" xmlns:tns="https://www.epam.com/products">

	<xs:simpleType name="ProductType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="convenience" />
			<xs:enumeration value="shopping" />
			<xs:enumeration value="speciality" />
			<xs:enumeration value="unsought" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Product">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="price" type="xs:integer" />
			<xs:element name="amount" type="xs:integer" />
			<xs:element name="description" type="xs:string" />
			<xs:element name="type" type="tns:ProductType" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="products">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="product" minOccurs="1" maxOccurs="unbounded"
					type="tns:Product" />

			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== VVATOR/jaxbPracticalTask/samples_data/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:products xmlns:tns="https://www.epam.com/products"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://www.epam.com/products products.xsd ">
	<product>
		<name>name0</name>
		<price>0</price>
		<amount>0</amount>
		<description>description0</description>
		<type>convenience</type>
	</product>
	<product>
		<name>name1</name>
		<price>10</price>
		<amount>10</amount>
		<description>description1</description>
		<type>convenience</type>
	</product>
	<product>
		<name>name2</name>
		<price>20</price>
		<amount>20</amount>
		<description>description2</description>
		<type>convenience</type>
	</product>
	<product>
		<name>name3</name>
		<price>30</price>
		<amount>30</amount>
		<description>description3</description>
		<type>convenience</type>
	</product>
	<product>
		<name>name4</name>
		<price>40</price>
		<amount>40</amount>
		<description>description4</description>
		<type>convenience</type>
	</product>
	<product>
		<name>name5</name>
		<price>50</price>
		<amount>50</amount>
		<description>description5</description>
		<type>convenience</type>
	</product>
	<product>
		<name>name6</name>
		<price>60</price>
		<amount>60</amount>
		<description>description6</description>
		<type>convenience</type>
	</product>
</tns:products>
